// <auto-generated />
namespace ECommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Totalupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Totalupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202507061259570_Totalupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
